SET FOREIGN_KEY_CHECKS = 0;

# CREATE DATABASE 
CREATE DATABASE flask_auth_db
	CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE flask_auth_db;

# USERS TABLE
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER AUTO_INCREMENT COMMENT'USER TABLE PRIMARY ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT'USER NAME',
    password VARCHAR(255) NOT NULL COMMENT'USER PASSWORD',
    role ENUM('admin', 'editor', 'viewer') NOT NULL DEFAULT 'viewer' COMMENT'USER ROLES',
    CONSTRAINT PK_USER_ID PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT ='TABLE TO STORE THE USER DETAILS';

COMMIT;

SET FOREIGN_KEY_CHECKS = 0;